import backendImg1 from '../../Assests/teams/BackendTechnologies/backendImg1.png';
import backendImg2 from '../../Assests/teams/BackendTechnologies/backendImg2.png';
import backendImg3 from '../../Assests/teams/BackendTechnologies/backendImg3.png';
import backendImg4 from '../../Assests/teams/BackendTechnologies/backendImg4.png';
import backendImg5 from '../../Assests/teams/BackendTechnologies/backendImg5.png';
import backendImg6 from '../../Assests/teams/BackendTechnologies/backendImg6.png';
import backendImg7 from '../../Assests/teams/BackendTechnologies/backendImg7.png';
import backendImg8 from '../../Assests/teams/BackendTechnologies/backendImg8.png';
import cloudImg1 from '../../Assests/teams/CloudTechnologies/cloudImg1.png';
import cloudImg2 from '../../Assests/teams/CloudTechnologies/cloudImg2.png';
import cloudImg3 from '../../Assests/teams/CloudTechnologies/cloudImg3.png';
import cmsImg1 from '../../Assests/teams/Cms/cmsImg1.png';
import cmsImg2 from '../../Assests/teams/Cms/cmsImg2.png';
import devOps1 from '../../Assests/teams/DevOps/devOps1.png';
import devOps2 from '../../Assests/teams/DevOps/devOps2.png';
import devOps3 from '../../Assests/teams/DevOps/devOps3.png';
import devOps4 from '../../Assests/teams/DevOps/devOps4.png';
import devOps5 from '../../Assests/teams/DevOps/devOps5.png';
import devOps6 from '../../Assests/teams/DevOps/devOps6.png';
import devOps7 from '../../Assests/teams/DevOps/devOps7.png';
import devOps8 from '../../Assests/teams/DevOps/devOps8.png';
import frameWork1 from '../../Assests/teams/Frameworks/frameWork1.png';
import frameWork2 from '../../Assests/teams/Frameworks/frameWork2.png';
import frameWork3 from '../../Assests/teams/Frameworks/frameWork3.png';
import frameWork4 from '../../Assests/teams/Frameworks/frameWork4.png';
import frameWork5 from '../../Assests/teams/Frameworks/frameWork5.png';
import frameWork6 from '../../Assests/teams/Frameworks/frameWork6.png';
import mobImg1 from '../../Assests/teams/MobileTechnologies/mobImg1.png';
import mobImg2 from '../../Assests/teams/MobileTechnologies/mobImg2.png';
import mobImg3 from '../../Assests/teams/MobileTechnologies/mobImg3.png';
import mobImg4 from '../../Assests/teams/MobileTechnologies/mobImg4.png';
import mobImg5 from '../../Assests/teams/MobileTechnologies/mobImg5.png';
import mobImg6 from '../../Assests/teams/MobileTechnologies/mobImg6.png';
import mobImg7 from '../../Assests/teams/MobileTechnologies/mobImg7.png';
import mobImg8 from '../../Assests/teams/MobileTechnologies/mobImg8.png';
import testingImg1 from '../../Assests/teams/Testing/testingImg1.png';
import testingImg2 from '../../Assests/teams/Testing/testingImg2.png';
import testingImg3 from '../../Assests/teams/Testing/testingImg3.png';
import testingImg4 from '../../Assests/teams/Testing/testingImg4.png';
import uxui1 from '../../Assests/teams/UiuxCreatives/uxui1.png';
import uxui2 from '../../Assests/teams/UiuxCreatives/uxui2.png';
import uxui3 from '../../Assests/teams/UiuxCreatives/uxui3.png';
import uxui4 from '../../Assests/teams/UiuxCreatives/uxui4.png';
import uxui5 from '../../Assests/teams/UiuxCreatives/uxui5.png';
import uxui6 from '../../Assests/teams/UiuxCreatives/uxui6.png';
import uxui7 from '../../Assests/teams/UiuxCreatives/uxui7.png';
import uxui8 from '../../Assests/teams/UiuxCreatives/uxui8.png';
import webImg1 from '../../Assests/teams/webTechnologies/webImg1.png';
import webImg2 from '../../Assests/teams/webTechnologies/webImg2.png';
import webImg3 from '../../Assests/teams/webTechnologies/webImg3.png';
import webImg4 from '../../Assests/teams/webTechnologies/webImg4.png';
import webImg5 from '../../Assests/teams/webTechnologies/webImg5.png';
import webImg6 from '../../Assests/teams/webTechnologies/webImg6.png';
import webImg7 from '../../Assests/teams/webTechnologies/webImg7.png';
import webImg8 from '../../Assests/teams/webTechnologies/webImg8.png';


export const backendTechnologies = [backendImg1,backendImg2,backendImg3,backendImg4,backendImg5,backendImg6,backendImg7,backendImg8];
export const cloudTechnologies = [cloudImg1,cloudImg2,cloudImg3];
export const cmsTechnologies = [cmsImg1,cmsImg2];
export const devOpsTechnologies = [devOps1,devOps2,devOps3,devOps4,devOps5,devOps6,devOps7,devOps8];
export const frameWorks = [frameWork1,frameWork2,frameWork3,frameWork4,frameWork5,frameWork6];
export const mobileTechnologies = [mobImg1,mobImg2,mobImg3,mobImg4,mobImg5,mobImg6,mobImg7,mobImg8];
export const testingTechnologies = [testingImg1,testingImg2,testingImg3,testingImg4];
export const uxuiTechnologies = [uxui1,uxui2,uxui3,uxui4,uxui5,uxui6,uxui7,uxui8];
export const webTechnologies = [webImg1,webImg2,webImg3,webImg4,webImg5,webImg6,webImg7,webImg8];